---
title: "Gov 50 Final Project"
author: "Layla Hijjawi"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone 1: Project thoughts

I am unsure of what exactly I want to explore in this project. I am potentially interested in exploring data related to racial disparities. I would also be interested into political data related to polarization. Because I live in Utah, I think it would be interesting to explore political data related to recent bills blocking gender affirming care. I'd also perhaps be interested in looking at data related to socioeconomic or racial disparities in the water crisis in Utah. 

## Milestone 2: Data Selection

Does oil revenue impact democratization or the likelihood of civil war in North African or Middle Eastern nations over time?

In this study, I plan to examine the extent to which oil as a significant source of revenue improves or worsens democratization or the likelihood of civil war in North Africa and the Middle East. I hypothesize that the likelihood of civil war will decrease if oil revenue is present. I believe this because extra revenue could allow governments to invest in stabilizing measures regardless of the type of regime or government. I also hypothesize that democratization will decrease further for North African and Middle Eastern nations that are non-democratic if oil revenues are present. I believe this because while extra revenue may allow nations to invest in stabilizing measures, if these nations are authoritarian, these extra measures may be similarly autocratic, thus decreasing democratization. 

My sample is comprised of North African and Middle Eastern countries from 1945 to 1999. My unit of analysis is a country (e.g. “Cyprus”). The explanatory variable of interest is whether a nation has greater than one-third of export revenues from fuels or not. The variable is coded = 1 for greater than one-third of export revenues from fuels and = 0 for the opposite. 

My outcome variable is whether or not civil war was occurring in a given year and polity, or the index of democratization for each nation. For civil war, the variable is coded = 1 if civil war is occurring in a given year and = 0 if it is not occurring. For polity, countries are assigned scores in a range of -10 to 10, with 10 representing a consolidated autocracy and -10 representing a consolidated autocracy. 

If I observe that civil war occurs less frequently and that polity decreases for nations with oil revenue, this would provide evidence for my hypothesis. However, if I observe that civil war occurs more frequently and that polity increases for nations with oil revenue, this would provide evidence against my thesis. 
